「制御」の補完の実装
smalruby/smalruby3-gui pull request #273
Opened 2020-12-11 12:55 UTC by laminne

### Resolves

https://github.com/smalruby/smalruby3-gui/issues/267

Controlの部分の補完機能を追加しました

2020-12-14 06:25 UTC, takaokouji requested changes

2020-12-14 06:25 UTC, takaokouji commented on src/containers/ruby-tab/control-completer.js
> +        });
コーディングスタイルのチェックにひっかかっていますので、以下のように修正して下さい。

```suggestion
        words.forEach(w => completions.push(w));
```

2020-12-14 06:25 UTC, takaokouji commented on src/containers/ruby-tab/control-completer.js
> +        let completions = [];
ここも
```suggestion
        const completions = [];
```

2020-12-14 06:26 UTC, takaokouji commented
@laminne 修正して、さらに rebase して再度レビュー依頼をお願いします。

2021-04-23 09:20 UTC, laminne commented
#277 と同じようなエラーでCIが落ちてしまいました...

2021-04-30 17:14 UTC, merged